
# Review - AutoClean library

### References
- [PyPi Docs *py-AutoClean*](https://pypi.org/project/py-AutoClean/)

!pip install py-AutoClean

In [15]:
from AutoClean import AutoClean
import seaborn as sns
import numpy as np

### load data

In [5]:
df = sns.load_dataset('planets')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

In [17]:
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [19]:
df.loc[df["mass"] == 7.10, "orbital_period"] = np.nan
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1             NaN   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

### Auto cleaning

In [9]:
AutoClean?

Init signature:
AutoClean(
    input_data,
    mode='auto',
    duplicates=False,
    missing_num=False,
    missing_categ=False,
    encode_categ=False,
    extract_datetime=False,
    outliers=False,
    outlier_param=1.5,
    logfile=True,
    verbose=False,
)
Docstring:      <no docstring>
Init docstring:
input_data (dataframe)..........Pandas dataframe
mode (str)......................define in which mode you want to run AutoClean
                                'auto' = sets all parameters to 'auto' and let AutoClean do the data cleaning automatically
                                'manual' = lets you choose which parameters/cleaning steps you want to perform

duplicates (str)................define if duplicates in the data should be handled
                                duplicates are rows where all features are identical
                                'auto' = automated handling, deletes all copies of duplicates except one
                                False = skips this step
missing_num (str)...............define how NUMERICAL missing values are handled
                                'auto' = automated handling
                                'linreg' = uses Linear Regression for predicting missing values
                                'knn' = uses K-NN algorithm for imputation
                                'mean','median' or 'most_frequent' = uses mean/median/mode imputatiom
                                'delete' = deletes observations with missing values
                                False = skips this step
missing_categ (str).............define how CATEGORICAL missing values are handled
                                'auto' = automated handling
                                'logreg' = uses Logistic Regression for predicting missing values
                                'knn' = uses K-NN algorithm for imputation
                                'most_frequent' = uses mode imputatiom
                                'delete' = deletes observations with missing values
                                False = skips this step
encode_categ (list).............encode CATEGORICAL features, takes a list as input
                                ['auto'] = automated encoding
                                ['onehot'] = one-hot-encode all CATEGORICAL features
                                ['label'] = label-encode all categ. features
                                to encode only specific features add the column name or index: ['onehot', ['col1', 2]]
                                False = skips this step
extract_datetime (str)..........define whether DATETIME type features should be extracted into separate features
                                to define granularity set to 'D'= day, 'M'= month, 'Y'= year, 'h'= hour, 'm'= minute or 's'= second
                                False = skips this step
outliers (str)..................define how outliers are handled
                                'winz' = replaces outliers through winsorization
                                'delete' = deletes observations containing outliers
                                oberservations are considered outliers if they are outside the lower and upper bound [Q1-1.5*IQR, Q3+1.5*IQR], where IQR is the interquartile range
                                to set a custom multiplier use the 'outlier_param' parameter
                                False = skips this step
outlier_param (int, float)......define the multiplier for the outlier bounds
logfile (bool)..................define whether to create a logile during the AutoClean process
                                logfile will be saved in working directory as "autoclean.log"
verbose (bool)..................define whether AutoClean logs will be printed in console

OUTPUT (dataframe)..............a cleaned Pandas dataframe, accessible through the 'output' instance
File:           ~/miniconda3/envs/analysis/lib/python3.7/site-packages/AutoClean/autoclean.py
Type:           type
Subclasses:

In [20]:
pipeline = AutoClean(df, mode='auto', verbose = True)

06-07-2023 18:44:30.08 - INFO - Started validation of input parameters...
06-07-2023 18:44:30.09 - INFO - Completed validation of input parameters
06-07-2023 18:44:30.09 - INFO - Started handling of duplicates... Method: "AUTO"
06-07-2023 18:44:30.10 - DEBUG - Deletion of 4 duplicate(s) succeeded
06-07-2023 18:44:30.10 - INFO - Completed handling of duplicates in 0.005927 seconds
06-07-2023 18:44:30.10 - INFO - Started handling of missing values...
06-07-2023 18:44:30.11 - INFO - Found a total of 782 missing value(s)
06-07-2023 18:44:30.11 - INFO - Started handling of NUMERICAL missing values... Method: "AUTO"
06-07-2023 18:44:30.15 - DEBUG - LINREG imputation of 1 value(s) succeeded for feature "orbital_period"
06-07-2023 18:44:30.21 - DEBUG - LINREG imputation of 278 value(s) succeeded for feature "mass"
06-07-2023 18:44:30.25 - DEBUG - LINREG imputation of 15 value(s) succeeded for feature "distance"
06-07-2023 18:44:30.31 - DEBUG - KNN imputation of 39 value(s) succeeded for feature "orbital_period"
06-07-2023 18:44:30.34 - DEBUG - KNN imputation of 240 value(s) succeeded for feature "mass"
06-07-2023 18:44:30.37 - DEBUG - KNN imputation of 209 value(s) succeeded for feature "distance"
06-07-2023 18:44:30.37 - INFO - Started handling of CATEGORICAL missing values... Method: "AUTO"
06-07-2023 18:44:30.48 - INFO - Completed handling of missing values in 0.377707 seconds
06-07-2023 18:44:30.49 - INFO - Started handling of outliers... Method: "WINZ"
06-07-2023 18:44:30.74 - DEBUG - Outlier imputation of 93 value(s) succeeded for feature "number"
06-07-2023 18:44:30.90 - DEBUG - Outlier imputation of 149 value(s) succeeded for feature "orbital_period"
06-07-2023 18:44:31.18 - DEBUG - Outlier imputation of 256 value(s) succeeded for feature "mass"
06-07-2023 18:44:31.29 - DEBUG - Outlier imputation of 83 value(s) succeeded for feature "distance"
06-07-2023 18:44:31.37 - DEBUG - Outlier imputation of 32 value(s) succeeded for feature "year"
06-07-2023 18:44:31.37 - INFO - Completed handling of outliers in 0.875715 seconds
06-07-2023 18:44:31.37 - INFO - Started conversion of DATETIME features... Granularity: s
06-07-2023 18:44:31.38 - INFO - Completed conversion of DATETIME features in 0.0043 seconds
06-07-2023 18:44:31.38 - INFO - Started encoding categorical features... Method: "AUTO"
06-07-2023 18:44:31.39 - DEBUG - Encoding to ONEHOT succeeded for feature "method"
06-07-2023 18:44:31.39 - INFO - Completed encoding of categorical features in 0.007335 seconds
06-07-2023 18:44:31.39 - INFO - Started feature type conversion...
06-07-2023 18:44:31.40 - DEBUG - Conversion to type INT succeeded for feature "number"
06-07-2023 18:44:31.41 - DEBUG - Conversion to type FLOAT succeeded for feature "orbital_period"
06-07-2023 18:44:31.42 - DEBUG - Conversion to type FLOAT succeeded for feature "mass"
06-07-2023 18:44:31.42 - DEBUG - Conversion to type FLOAT succeeded for feature "distance"
06-07-2023 18:44:31.43 - DEBUG - Conversion to type INT succeeded for feature "year"
06-07-2023 18:44:31.44 - DEBUG - Conversion to type INT succeeded for feature "method_Astrometry"
06-07-2023 18:44:31.45 - DEBUG - Conversion to type INT succeeded for feature "method_Eclipse Timing Variations"
06-07-2023 18:44:31.46 - DEBUG - Conversion to type INT succeeded for feature "method_Imaging"
06-07-2023 18:44:31.47 - DEBUG - Conversion to type INT succeeded for feature "method_Microlensing"
06-07-2023 18:44:31.48 - DEBUG - Conversion to type INT succeeded for feature "method_Orbital Brightness Modulation"
06-07-2023 18:44:31.49 - DEBUG - Conversion to type INT succeeded for feature "method_Pulsar Timing"
06-07-2023 18:44:31.49 - DEBUG - Conversion to type INT succeeded for feature "method_Pulsation Timing Variations"
06-07-2023 18:44:31.49 - DEBUG - Conversion to type INT succeeded for feature "method_Radial Velocity"
06-07-2023 18:44:31.50 - DEBUG - Conversion to type INT succeeded for feature "method_Transit"
06-07-2023 18:44:31.51 - DEBUG - Conversion to type INT succeeded for feature "method_Transit Timing Variations"
06-07-2023 18:44:31.51 - INFO - Completed feature type conversion for 15 feature(s) in 0.112747 seconds
06-07-2023 18:44:31.51 - INFO - AutoClean process completed in 1.443202 seconds

Logfile saved to: /Users/juan/Workspace/projects/utilsDS/notebooks/feature_engineering/auto_data_preparation/autoclean.log

In [10]:
dir(pipeline)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_clean_data',
 '_initialize_logger',
 '_validate_params',
 'count_missing',
 'duplicates',
 'encode_categ',
 'extract_datetime',
 'missing_categ',
 'missing_num',
 'mode',
 'outlier_param',
 'outliers',
 'output']

In [21]:
pipeline.output

,method,number,orbital_period,mass,distance,year,method_Astrometry,method_Eclipse Timing Variations,method_Imaging,method_Microlensing,method_Orbital Brightness Modulation,method_Pulsar Timing,method_Pulsation Timing Variations,method_Radial Velocity,method_Transit,method_Transit Timing Variations
0,Radial Velocity,1,476.553352,7.100000,77.40,2006,0,0,0,0,0,0,0,1,0,0
1,Radial Velocity,1,874.774000,2.210000,56.95,2008,0,0,0,0,0,0,0,1,0,0
2,Radial Velocity,1,763.000000,2.600000,19.84,2011,0,0,0,0,0,0,0,1,0,0
3,Radial Velocity,1,326.030000,19.400000,110.62,2007,0,0,0,0,0,0,0,1,0,0
4,Radial Velocity,1,516.220000,10.500000,119.47,2009,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1026,Transit,1,3.941507,4.582361,172.00,2006,0,0,0,0,0,0,0,0,1,0
1027,Transit,1,2.615864,2.560458,148.00,2007,0,0,0,0,0,0,0,0,1,0
1028,Transit,1,3.191524,3.970132,174.00,2007,0,0,0,0,0,0,0,0,1,0
1029,Transit,1,4.125083,24.747639,293.00,2008,0,0,0,0,0,0,0,0,1,0
1030,Transit,1,4.187757,14.187916,260.00,2008,0,0,0,0,0,0,0,0,1,0